
version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    container_name: db
    restart: always
    volumes:
      - rent_bike_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - rent_bike_value:/var/html/static/
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis

  celery:
    image: ${DOCKER_HUB_USERNAME}/rent_bike:latest
    container_name: celery
    restart: always
    command: celery -A config worker -l INFO
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  backend:
    image: ${DOCKER_HUB_USERNAME}/rent_bike:latest
    container_name: backend
    restart: always
    volumes:
      - rent_bike_value:/app/static/
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - ./.env

volumes:
  rent_bike_value:
  rent_bike_data:
