# Generated by Django 5.0.6 on 2024-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bicycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Модель"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
            ],
            options={
                "verbose_name": "Велосипед",
                "verbose_name_plural": "Велосипеды",
                "ordering": ["model"],
            },
        ),
    ]
