# Generated by Django 5.0.6 on 2024-06-28 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "rental_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Стоимость аренды в час",
                    ),
                ),
            ],
            options={
                "verbose_name": "Марка велосипеда",
                "verbose_name_plural": "Марки велосипедов",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Bicycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bicycles.brand",
                        verbose_name="Марка Велосипеда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Велосипед",
                "verbose_name_plural": "Велосипеды",
                "ordering": ["brand"],
            },
        ),
    ]
