# Generated by Django 5.0.6 on 2024-06-29 14:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bicycle",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bicycles",
                to="bicycles.brand",
                verbose_name="Марка Велосипеда",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="rental_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0"), "Цена не может быть меньше 0."
                    )
                ],
                verbose_name="Цена аренды в час",
            ),
        ),
    ]
