# Generated by Django 5.0.6 on 2024-06-29 14:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bicycles", "0002_alter_bicycle_brand_alter_brand_rental_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Начало аренды",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        null=True, verbose_name="Конец аренды"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"),
                                "Стоимость не может быть меньше 0.",
                            )
                        ],
                        verbose_name="Стоимость аренды",
                    ),
                ),
                (
                    "bicycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bicycles.bicycle",
                        verbose_name="велоспед",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Арендатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аренда",
                "verbose_name_plural": "Аренды",
                "default_related_name": "rents",
            },
        ),
    ]
