# Generated by Django 5.0.6 on 2024-06-29 16:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0"), "Стоимость не может быть меньше 0."
                    )
                ],
                verbose_name="Стоимость аренды",
            ),
        ),
    ]
